### ISSUE TITLE
the Y Berlin @ MOOS

### ISSUE THREAD

**Issue by IvaTomevska** [blockchainweek/data#34]
we want to offer the the Y berlin at MOOS :: a regenerative community as a venue for berlin blockchain week 2024. we have hosted residencies, (un)hackathons, and narrative design experiences for web3 and regen communities ver the past 12 years. find more info here :: 

www.moos.garden
moos.super.site
www.moos.space

**Comment by q9f** [comment]
This? https://blockchainweek.berlin/24/place/moos
