### ISSUE TITLE
[NEW]: CRYPTO2030

### ISSUE THREAD

**Issue by CRYPTO-2030** [blockchainweek/data#43]
**22 May 2024, 11am to 6pm** Venue: [CV Labs @ Lisk Centre](https://maps.app.goo.gl/tVU8EoAJmboJvv3A7)

**CRYPTO2030** serves as an ideal platform for industry leaders, experts and innovators to come together. This event was hosted in an interactive format where thematic dialogues, roundtables and networking opportunities abounded. 

Our goal for **CRYPTO2030** is to foster a productive environment where influential voices could exchange ideas and collectively propel the advancement of the Web3 space.

_Proudly hosted by **SMART-compliance** and **SMART-shift**, supported by **BerChain**, **Crypto Valley Association**, venue partner **CV Labs**._

For more information, please visit [c2030.org](http://c2030.org/)

**Comment by kuzdogan** [comment]
Your event is live please double check if everything is correct :) https://blockchainweek.berlin/24
