### ISSUE TITLE
[NEW]: Staatssekretär Berlin Opens up Web3 Drone Corridor 

### ISSUE THREAD

**Issue by SantaBerlin** [blockchainweek/data#57]
Please tell us where we can find a list of your event's speakers so that we can add them to the BBW dataset.

Staatssekretär in der Senatsverwaltung für Wirtschaft, Energie und Betriebe des Landes Berlin, Dr. Fischer will open up the Staex Web3 Drone Corridor during Blockchain Week on May 21, 2024. 

https://staex.io/web3-drone-corridor

**Comment by kuzdogan** [comment]
Hi, not sure if I understand what this is for. Is this resolved with the recent update?
