### ISSUE TITLE
[UPDATE]: afk berlin image  

### ISSUE THREAD

**Issue by mariapaulafn** [blockchainweek/data#66]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "afk with Lens & friends"


# A logo attachment
logo = "logo.png"
![Square (1)](https://github.com/blockchainweek/data/assets/27913589/96f46a77-9b0c-41c1-9dac-8dce0453e62e)
![Square (1)](https://github.com/blockchainweek/data/assets/27913589/d198ae79-0f42-4f04-ac56-71060aee651c)

**Comment by kuzdogan** [comment]
Updated :) https://blockchainweek.berlin/24/event/lens
