### ISSUE TITLE
[NEW]: INDUSTRY WEB3 DRONE CORRIDOR

### ISSUE THREAD

**Issue by SantaBerlin** [blockchainweek/data#7]
First in the World #Web3 Drone Corridor — Launch!

Who said Web3 does not have Industry initiatives that matter? 

Berlin-based startup , Staex — zero-trust network automation for IoT — is launching the first Web3 Drone corridor in the world! Together with Vantage Towers, REWE Group's paymenttools, Lisk (L2 on ethereum), a leading supplier of commercial drones, and a global telco, they will showcase industry utilizing Web3 tools to innovate, create new business opportunities, and even realize machine-to-machine payments. 

For more information or involvement and sponsorship: https://staex.io/web3-drone-corridor or contact:
GitHub @SantaBerlin or paksy@staex.io
Paksy Plackis-Cheng, Chief Strategy Officer, Staex GmbH

The official physical drone launch will happen during Blockchain Week 2024! Stay tuned for exact launch date. 

![staex-logo](https://github.com/blockchainweek/data/assets/163290027/bf14d48c-c383-4080-a576-85ff9adc0120)

![Vantage Towers ](https://github.com/blockchainweek/data/assets/163290027/3a24b15d-3306-4f63-a4cc-b3e65b115a66)

![Rewe Group paymenttools](https://github.com/blockchainweek/data/assets/163290027/5ab5ec61-a107-45f4-90a8-b4e44d2cf14b)

**Comment by q9f** [comment]
Please use the template once you know more about the event! :)
