### ISSUE TITLE
Blockhaus Afterparty by LUKSO with Google Cloud, SheFi & Guild

### ISSUE THREAD

**Issue by louiejoconnor** [blockchainweek/data#82]
**Luma**: https://lu.ma/ok55cmmf​

Join us in Berlin with [Google Cloud](https://twitter.com/googlecloud, [SheFi](https://twitter.com/shefiorg), and [Guild](https://twitter.com/guildxyz), with onsite activations by [Proof:of by Ensō](https://twitter.com/enso_collective) and [DistrictVR](https://twitter.com/TheDistrictVR), as we wrap UP Berlin Blockchain Week with a party you won’t want to miss. 

**​THE PLAYGROUNDS:** 
**☁️ Rooftop:** Google Cloud Zen Lounge
**🥐 4th Floor:** She-Fi and Snacks
**🎛️ 3rd Floor:** Pink Disco Zone

**​BEAT IMMERSION:**
**8pm - 10pm:** Ahmed & Jappa (B-2-B)
**10pm - 11:30pm:** [Denyo](https://g.co/kgs/K31cbYd) ([DistrictVR](https://twitter.com/TheDistrictVR)) 
**11:30pm onwards:** [LEDFUT](https://twitter.com/ledfut_dj) ([DistrictVR](https://twitter.com/TheDistrictVR))

**​DETAILS** 
**📅 Date:** May 24th, 2024
**🕒 Time:** 8pm - late

​RSVP required for all attendees.

Create your Universal Profile before attending to be able to engage with the event activations – get started [here](https://universalprofile.cloud/).
![LUKSO Template — Instagram Post (1080x1080px)](https://github.com/blockchainweek/data/assets/57448030/f258710a-7079-4bd7-92ea-509da31a38e3)

**Comment by kuzdogan** [comment]
Your event is live :) https://blockchainweek.berlin/24 please check if everything's correct
