### ISSUE TITLE
UPDATE: AIxHOPE

### ISSUE THREAD

**Issue by madviiii** [blockchainweek/data#94]
Please update the cover photo for the ai x hope event on 24th May

thanks!

![AIHOPEgreen](https://github.com/blockchainweek/data/assets/102733809/407d9cab-a656-448c-a1e9-a1248e62e00a)

**Comment by madviiii** [comment]
other changes: 🙏🙏🙏🙏🙏

Title: AI x HOPE

Website: https://lu.ma/aix

docs: **please remove link!** 

Organisers: Seed Club Ventures, Foresight Institute

Contact: NiMA

Speakers: please remove link. this is closed. 

Text:

AI x Hope: Towards Futures of Human-AI Interdependence

We stand at a crucial point in shaping how Human-AI cooperation will evolve and are witnessing the birth of a new internet. We aim to approach this flippening with [Existential Hope](https://www.existentialhope.com/), and foster futures where humans and machines coexist to flourish ✨. 

​Our belief is that a healthy and harmonious development of decentralized artificial general intelligence (AGI) can arise from an enlightened vantage point. Specifically, we hope to empower builders, researchers, creators and investors exploring positive futures and protocols at the intersection of AI, crypto and creativity, with AI x Hope as an enabler for coordination in sharing technical, research-based and values-aligned perspectives.

We will converge through panel discussions, keynotes and workshops and think far and wide on the ways to align the nascent AI x crypto space for this new paradigm, where our collective synergy—in data, values and protocols—is all we need. 

Curated by [Seed Club Ventures](https://seedclub.ventures/) and [Foresight Institute](https://foresight.org/).

Tentative [Schedule](https://docs.google.com/spreadsheets/d/1HJnKxdquXE1bI7t5b8BbHHkSFgQL9MCQEvTQ5Xf0V2k/edit?usp=sharing)

​
~~
SPEAKERS
Join us to talk with top researchers, founders, creators, and investors in decentralized AI, including:

​[Holly Herndon](https://twitter.com/hollyherndon), Co-Founder @ [Spawning.ai](http://spawning.ai/)
[Matt Dryhurst](https://twitter.com/matdryhurst), Co-Founder @ [Spawning.ai](http://spawning.ai/)

​[Lou](https://twitter.com/louviq), Program Director @ Foresight Institute
[NiMA](https://twitter.com/insideNiMA), Instigator @ Seed Club Ventures

​

​[Dr. Richard Blythman](https://x.com/richardblythman?t=wM-eZdpZvp54Kqu2Be61PQ&s=35), Co-Founder @ Naptha
[Illia Polosukhin](https://twitter.com/ilblackdragon), Co-Founder @ NEARProtocol
[Emad Mostaque](https://twitter.com/EMostaque), Founder @ [Schelling.AI](http://schelling.ai/), Stability AI
[Puja Ohlhaver](https://twitter.com/pujaohlhaver), Pluralist, Technologist
[Martin Köppelmann](https://twitter.com/koeppelmann), Co-Founder @ Gnosis
[Vincent Weisser](https://twitter.com/vincentweisser), CEO @ Prime Intellect

​[Trent McConaghy](http://www.twitter.com/trentmc0), Founder @ Ocean Protocol
[Sofiane Delloue](https://twitter.com/sofiane_nco), Co-Founder @ Newcoin
[Nick Naraghi,](https://twitter.com/0xNN2) Co-Founder @ Hats Protocol
[David Minarsch](https://twitter.com/david_enim), Co-Founder @ Valory/Autonolas
[Gabriel Fior](https://www.linkedin.com/in/gabrielfior/), Crypto + AI @ Gnosis
[Fatemeh Fannizadeh, ](https://twitter.com/Fatalmeh)Legal @ Swarm


[AGENDA](https://docs.google.com/spreadsheets/d/1HJnKxdquXE1bI7t5b8BbHHkSFgQL9MCQEvTQ5Xf0V2k/edit?usp=sharing)

14:00 ~ Welcome Sessions
15:00-19:00 ~ Main Talks & Workshop Sessions
19:00-22:00 ~ Dinner & Social Gathering (in the summer garden & next-door cafe westberlin)
22:00+ ~ TBD AFTERPARTY, berlin-style (You will be invited)

Beanbag chill areas + summer garden open during the entire event for you.


Excited and looking some good resources on x-hope? Check out [Existential Hope](https://www.existentialhope.com/)!

​We're grateful to our friends from [Molecule](https://www.molecule.xyz/) for hosting this event at their Berlin HQ. Event production supported by Pretopia Ventures GmbH.

​
SEED CLUB VENTURES
[Seed Club Ventures](https://seedclub.ventures/) is a Venture DAO backing early-stage founders building at the intersection of web3 and community. With a membership of 60+ leading innovators and investors in crypto, we are diverse in our ability to support projects throughout their life cycle. Launched in partnership with [Seed Club](https://www.seedclub.xyz/) — the leading network for builders at the intersection of crypto, culture, and community — our mission is to build a community-owned internet.
‍
‍
FORESIGHT INSTITUTE
[Existential Hope](http://existentialhope.com/) is a [Foresight Institute](https://foresight.org/) project. Foresight is a non-profit that supports the beneficial development of high-impact technologies. From nanotech, to BCI, space exploration, cryptocommerce, biotech and AI, we gather leading minds to advance research and accelerate progress toward flourishing futures. Existential Hope project is the contextualizer of all our work. As we advance technology and science, we also want to ensure that we are progressing positive futures, and decreasing x-risks.

**Comment by kuzdogan** [comment]
Made the changes. The only thing is, it's not possible to add GIFs as covers so I made it a PNG.

Please double check https://blockchainweek.berlin/24
